name: factorial
description: Factorial app.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2

  dio: ^4.0.6

  flutter:
    sdk: flutter
  get_it: ^7.2.0
  domain:
    path: packages/domain
  data:
    path: packages/data
  presentation:
    path: packages/presentation


dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  build_runner: 2.2.0
  injectable_generator: 1.5.4

flutter:
  uses-material-design: true
