# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do

  desc "Build and upload to FAD"
  lane :upload_fad do |options|
    firebase_app_distribution(
      app: options[:firebase_app_id],
      firebase_cli_token: options[:firebase_cli_token],
      groups: "internal",
      android_artifact_path: "../build/app/outputs/flutter-apk/app-debug.apk",
      android_artifact_type: "APK",
      release_notes: "Profile AWS environment"
    )
  end
end
