name: build-apps

on:
  push:
    branches:
      - '**'
jobs:
  build:
    runs-on: macos-12
    steps:
#      - uses: subosito/flutter-action@v2
#        with:
#          flutter-version: '3.0.5'
#          channel: 'stable'
#      - run: flutter --version
      - name: Debug check
        run: echo $GITHUB_WORKSPACE
      - name: Debug check1
        run: ls
      - name: Build APK
        run: flutter build apk --debug

