name: build-apps

on:
  push:
    branches:
      - 'feature/**'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ruby/setup-ruby@v1.118.0
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.0.5'
          channel: 'stable'
      - run: flutter --version
      - name: Pub get
        run: flutter pub get
      - name: Build APK
        run: flutter build apk --debug
      - name: Upload APK
        run: | 
          cd android 
          fastlane add_plugin firebase_app_distribution
          fastlane upload_fad firebase_app_id:${{secrets.FIREBASE_ANDROID_APP_ID}} firebase_cli_token:${{secrets.FIREBASE_TOKEN}}

#      - name: upload artifact to Firebase App Distribution
#        uses: wzieba/Firebase-Distribution-Github-Action@v1.3.5
#        with:
#          appId: ${{secrets.FIREBASE_ANDROID_APP_ID}}
#          token: ${{secrets.FIREBASE_TOKEN}}
#          groups: testers
#          file: build/app/outputs/flutter-apk/app-debug.apk